version: "3"

services:
  namenode:
    image: wxwmatt/hadoop-namenode:2.1.1-hadoop3.3.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    working_dir: /
    environment:
      - CLUSTER_NAME=test
      - HOME=/
      - SPARK_HOME=/usr/local/lib/python3.7/dist-packages/pyspark
      - HIVE_HOME=/hive/apache-hive-3.1.3-bin
    env_file:
      - ../../../docker-hadoop-spark/hadoop.env

  datanode:
    image: wxwmatt/hadoop-datanode:2.1.1-hadoop3.3.1-java8
    container_name: datanode
    restart: always
    ports:
      - 9864:9864
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ../../../docker-hadoop-spark/hadoop.env

  resourcemanager:
    image: wxwmatt/hadoop-resourcemanager:2.1.1-hadoop3.3.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ../../../docker-hadoop-spark/hadoop.env

  nodemanager:
    image: wxwmatt/hadoop-nodemanager:2.1.1-hadoop3.3.1-java8
    container_name: nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ../../../docker-hadoop-spark/hadoop.env

  hadoop-spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: hadoop-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
      - spark_volume:/spark

  hadoop-spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: hadoop-spark-worker-1
    depends_on:
      - hadoop-spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://hadoop-spark-master:7077"
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g

  hadoop-spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: hadoop-spark-worker-2
    depends_on:
      - hadoop-spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://hadoop-spark-master:7077"
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g

  hadoop-zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: hadoop-zeppelin
    depends_on:
      - hadoop-spark-master
    ports:
      - "8083:8080"
    volumes:
      - ./zeppelin/notebook:/opt/zeppelin/notebook
      - ./zeppelin/conf:/opt/zeppelin/conf
      - ./zeppelin/dataset:/opt/zeppelin/dataset
      - spark_volume:/opt/zeppelin/spark

    environment:
      - "SPARK_HOME=/opt/zeppelin/spark"
      - "SPARK_MASTER=spark://hadoop-spark-master:7077"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  spark_volume:
